//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MingleView.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MingleView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static byte[] AvalonDock {
            get {
                object obj = ResourceManager.GetObject("AvalonDock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] AxInterop_RDPCOMAPILib {
            get {
                object obj = ResourceManager.GetObject("AxInterop_RDPCOMAPILib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Interop_NetFwTypeLib {
            get {
                object obj = ResourceManager.GetObject("Interop_NetFwTypeLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Interop_RDPCOMAPILib {
            get {
                object obj = ResourceManager.GetObject("Interop_RDPCOMAPILib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Dialog.
        /// </summary>
        public static string MainWindowViewModel_Command_ChatView {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ChatView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant List.
        /// </summary>
        public static string MainWindowViewModel_Command_ParticipantView {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ParticipantView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Launch View.
        /// </summary>
        public static string MainWindowViewModel_Command_QuickLaunchView {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_QuickLaunchView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Desktop.
        /// </summary>
        public static string MainWindowViewModel_Command_RemoteScreenView {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_RemoteScreenView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MingleView.
        /// </summary>
        public static string MainWindowViewModel_DisplayName {
            get {
                return ResourceManager.GetString("MainWindowViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Join Meeting.
        /// </summary>
        public static string MainWindowViewModel_Menu_Join_Meeting {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Menu_Join_Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Leave Meeting.
        /// </summary>
        public static string MainWindowViewModel_Menu_Leave_Meeting {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Menu_Leave_Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start Meeting.
        /// </summary>
        public static string MainWindowViewModel_Menu_Start_Meeting {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Menu_Start_Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PEERIDENTITYEXPORT VERSION=&quot;1.0&quot;&gt;&lt;PEERNAME&gt;cf50eb3649588a64e5fbc71f593b5600fb7f95df&lt;/PEERNAME&gt;&lt;DATA xmlns:dt=&quot;urn:schemas-microsoft-com:datatypes&quot; dt:dt=&quot;bin.base64&quot;&gt;TQBJAEkASABvAEEASQBCAEEAegBDAEMAQgAxAHcARwBDAFMAcQBHAFMASQBiADMARABRAEUA
        ///SABBAGEAQwBDAEIAMAAwAEUAZwBnAGQASgBNAEkASQBIAFIAVABDAEMAQQA3ADQARwBDAFMA
        ///cQBHAFMASQBiADMARABRAEUASAANAAoAQQBhAEMAQwBBADYAOABFAGcAZwBPAHIATQBJAEkA
        ///RABwAHoAQwBDAEEANgBNAEcAQwB5AHEARwBTAEkAYgAzAEQAUQBFAE0AQwBnAEUAQwBvAEkA
        ///SQBDAHQAagBDAEMAQQByAEkAdwBIAEEAWQBLAEsAbwBaAEkAa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string P2PDNS_LANOI_IDENTITY {
            get {
                return ResourceManager.GetString("P2PDNS_LANOI_IDENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cf50eb3649588a64e5fbc71f593b5600fb7f95df.
        /// </summary>
        public static string P2PDNS_LANOI_PEER_NAME {
            get {
                return ResourceManager.GetString("P2PDNS_LANOI_PEER_NAME", resourceCulture);
            }
        }
        
        public static System.Drawing.Icon Participant {
            get {
                object obj = ResourceManager.GetObject("Participant", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Icon Presenter {
            get {
                object obj = ResourceManager.GetObject("Presenter", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
