//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MingleView.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MingleView.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like to update mingleview to newer version?.
        /// </summary>
        public static string AutoUpdater_Ask_For_update {
            get {
                return ResourceManager.GetString("AutoUpdater_Ask_For_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Dialog.
        /// </summary>
        public static string MainWindowViewModel_Command_ChatView {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ChatView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant List.
        /// </summary>
        public static string MainWindowViewModel_Command_ParticipantView {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ParticipantView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Launch View.
        /// </summary>
        public static string MainWindowViewModel_Command_QuickLaunchView {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_QuickLaunchView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Desktop.
        /// </summary>
        public static string MainWindowViewModel_Command_RemoteScreenView {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_RemoteScreenView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MingleView.
        /// </summary>
        public static string MainWindowViewModel_DisplayName {
            get {
                return ResourceManager.GetString("MainWindowViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait a while....
        /// </summary>
        public static string MainWindowViewModel_Meeting_Leaving_caption {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Meeting_Leaving_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while meeting is being initialized...
        /// </summary>
        public static string MainWindowViewModel_Meeting_Progress_caption {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Meeting_Progress_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string MainWindowViewModel_Menu_About_MingleView {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Menu_About_MingleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string MainWindowViewModel_Menu_Exit {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Join Meeting.
        /// </summary>
        public static string MainWindowViewModel_Menu_Join_Meeting {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Menu_Join_Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Leave Meeting.
        /// </summary>
        public static string MainWindowViewModel_Menu_Leave_Meeting {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Menu_Leave_Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send _Error Report.
        /// </summary>
        public static string MainWindowViewModel_Menu_Show_Error_Report {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Menu_Show_Error_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Start Meeting.
        /// </summary>
        public static string MainWindowViewModel_Menu_Start_Meeting {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Menu_Start_Meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PEERIDENTITYEXPORT VERSION=&quot;1.0&quot;&gt;&lt;PEERNAME&gt;cf50eb3649588a64e5fbc71f593b5600fb7f95df&lt;/PEERNAME&gt;&lt;DATA xmlns:dt=&quot;urn:schemas-microsoft-com:datatypes&quot; dt:dt=&quot;bin.base64&quot;&gt;TQBJAEkASABvAEEASQBCAEEAegBDAEMAQgAxAHcARwBDAFMAcQBHAFMASQBiADMARABRAEUA
        ///SABBAGEAQwBDAEIAMAAwAEUAZwBnAGQASgBNAEkASQBIAFIAVABDAEMAQQA3ADQARwBDAFMA
        ///cQBHAFMASQBiADMARABRAEUASAANAAoAQQBhAEMAQwBBADYAOABFAGcAZwBPAHIATQBJAEkA
        ///RABwAHoAQwBDAEEANgBNAEcAQwB5AHEARwBTAEkAYgAzAEQAUQBFAE0AQwBnAEUAQwBvAEkA
        ///SQBDAHQAagBDAEMAQQByAEkAdwBIAEEAWQBLAEsAbwBaAEkAa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string P2PDNS_LANOI_IDENTITY {
            get {
                return ResourceManager.GetString("P2PDNS_LANOI_IDENTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cf50eb3649588a64e5fbc71f593b5600fb7f95df.
        /// </summary>
        public static string P2PDNS_LANOI_PEER_NAME {
            get {
                return ResourceManager.GetString("P2PDNS_LANOI_PEER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  IPv6 address not found. Mingleview requires IPv6 to connect with other participants over the internet. Please click &quot;Contact Support&quot; from &quot;Help&quot; to get further assistance..
        /// </summary>
        public static string P2PDNS_NoGlobalIPv6_ErrorMsg {
            get {
                return ResourceManager.GetString("P2PDNS_NoGlobalIPv6_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register the meeting ID. Reason:.
        /// </summary>
        public static string P2PDNS_RegisterDNS_ErrorMsg {
            get {
                return ResourceManager.GetString("P2PDNS_RegisterDNS_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to resolve the  meeting ID. Reason:.
        /// </summary>
        public static string P2PDNS_ResolveDNS_ErrorMsg {
            get {
                return ResourceManager.GetString("P2PDNS_ResolveDNS_ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the meeting ID. Reason:.
        /// </summary>
        public static string P2PMesh_Mesh_OpenErrorMsg {
            get {
                return ResourceManager.GetString("P2PMesh_Mesh_OpenErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the custom resolver host. Reason:.
        /// </summary>
        public static string P2PResolver_Host_OpenErrorMesg {
            get {
                return ResourceManager.GetString("P2PResolver_Host_OpenErrorMesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Sharing Desktop.
        /// </summary>
        public static string QuickLaunchViewModel_Start_ShareDesktop_Button_Text {
            get {
                return ResourceManager.GetString("QuickLaunchViewModel_Start_ShareDesktop_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Sharing Desktop.
        /// </summary>
        public static string QuickLaunchViewModel_Stop_ShareDesktop_Button_Text {
            get {
                return ResourceManager.GetString("QuickLaunchViewModel_Stop_ShareDesktop_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Control.
        /// </summary>
        public static string RemoteScreenViewModel_Release_Control_Text {
            get {
                return ResourceManager.GetString("RemoteScreenViewModel_Release_Control_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Control.
        /// </summary>
        public static string RemoteScreenViewModel_Request_Control_Text {
            get {
                return ResourceManager.GetString("RemoteScreenViewModel_Request_Control_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to size.
        /// </summary>
        public static string RemoteScreenViewModel_Screen_Fit_to_size {
            get {
                return ResourceManager.GetString("RemoteScreenViewModel_Screen_Fit_to_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string RemoteScreenViewModel_Screen_restore {
            get {
                return ResourceManager.GetString("RemoteScreenViewModel_Screen_restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft .NET Framework 3.5 has to be installed for running mingleview.       Click on YES to download Microsoft .NET Framework 3.5..
        /// </summary>
        public static string SelfInstaller_DotNet_Install_Prompt {
            get {
                return ResourceManager.GetString("SelfInstaller_DotNet_Install_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error report sent to support. Further assistance will be provided by support..
        /// </summary>
        public static string SendErrorReportViewModel_Send_Success {
            get {
                return ResourceManager.GetString("SendErrorReportViewModel_Send_Success", resourceCulture);
            }
        }
    }
}
